### PR TITLE
Update configuration-items-for-devices-managed-with-the-client.md

### PR DESCRIPTION
**Pull request by cjgronlund**
FIxed minor grammatical typo.

### CODE REVIEW

**Comment by cjgronlund** [comment]
@robstackmsft

**Comment by dougeby** [comment]
@cjgronlund Thanks Carolyn!!  I've merged the fix.

**Comment by dougeby** [comment]
@robstackmsft Hey Rob, I went ahead and merged the fix. Simple typo.

**Comment by robstackmsft** [comment]
@dougeby Thanks Doug!

**Pull request merged**
