### PR TITLE
Education has same support as Enterprise, Pro

### PR DESCRIPTION
**Pull request by npherson**

### CODE REVIEW

**Comment by arob98** [comment]
Review in process.

**Comment by Brenduns** [comment]
Investigating with engineering. Not all skus are supported nor tested. Education has been discussed before but was omitted during a recent in-depth dive.  Will get current guidance/confirmation before we can accept this.

**Comment by arob98** [comment]
@Brenduns  any update?

**Comment by Brenduns** [comment]
After consult, yes, education is approved for support.  Further changes to this table are pending, possibly as soon as next week.

**Pull request merged**
